### PR TITLE
add PWD local config files

### PR DESCRIPTION
**Pull request by rupurt**
# Description

Read config file from `$PWD` if present

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Documentation

- [x] the change is mentioned in the `## [Unreleased]` section of `CHANGELOG.md`
- [x] the configuration yaml was changed and the example config in `README.md` was updated
- [x] a usage example was added to `README.md`

### CODE REVIEW

**Comment by d-rk** [comment]
Hey @rupurt ,
Just out of curiosity: what is your use case for this?

**Comment by rupurt** [comment]
@d-rk I work on several teams with different kafka configurations. Currently we have the configs local to the repository and have to provide the -C option to `kafkactl`

**Comment by d-rk** [comment]
@rupurt I tested your change. One problem is that when no config file is present a default config will be created in the first folder of `configPaths` which now resolves to `$PWD/.config/kafkactl`.

This is not wanted, but could be fixed.

But when thinking about the issue,  I found it rather weird that a folder structure is expected when reading the config from the working directory.

I decided to do it differently (see https://github.com/deviceinsight/kafkactl/pull/163) and look for a config at `$PWD/kafkactl.yml`.

I hope this also supports your usecase. If not let me know.
I will close this PR though.

**Comment by rupurt** [comment]
Sweet. That will do the job!

Thank you

**Pull request closed without merging**
