### PR TITLE
Add default config generation if no config found

### PR DESCRIPTION
**Pull request by SmilingNavern**
For issue #22 
I am not quite sure about implementation. I've tried to found a way to ask viper if there is config file, but found none. So it's a glob checking here for a file. Maybe should move some constants like 'yml' and 'config' to variables.

### CODE REVIEW

**Comment by random-dwi** [comment]
You can check whether the config file exists with something like this:
```
if err := viper.ReadInConfig(); err != nil {
    if _, ok := err.(viper.ConfigFileNotFoundError); ok {
        // Config file not found; ignore error if desired
    } else {
        // Config file was found but another error was produced
    }
}
```

**Comment by SmilingNavern** [comment]
@random-dwi hi. Yeah, i thought about it, but i am not sure if this is good approach because there can be side effects of readinconfig.

What do you think i should do? Generate config in error section?

**Comment by dwi-di** [comment]
@SmilingNavern thats why the code block checks for the specific error `ConfigFileNotFoundError` and only in this case the default config should be generated.

**Comment by SmilingNavern** [comment]
@dwi-di understood, i will rewrite it. Thanks.

**Comment by SmilingNavern** [comment]
I've rewritten it. Check please

**Comment by dwi-di** [comment]
Looks good :+1: 
I added some minor changes for the error handling

**Comment by SmilingNavern** [comment]
Cool, thank you for review.

**Pull request merged**
