### PR TITLE
extend the documentation of the command completion of zsh

### PR DESCRIPTION
**Pull request by Am3o**
# Description

In the documentation is a little mistake about the zsh completion. The documentation of zsh recommends installing all completions to the `$ZSH/cache/completions` directory and reloading the completion plugin. The file `.zprofile` is executed in every new terminal session. So every time the completion is activated. It's more explicit.

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

## Documentation
- [x] fix the zsh completion in`README.md`

### CODE REVIEW

**Comment by tarys** [comment]
Nice, thanks a lot!
Looking forward for merge and new release :)

**Comment by Am3o** [comment]
Its a pleasure and i really love the tool! 

Sorry for the force pushes, I had to change my git identity

**Comment by Am3o** [comment]
I thought a rebase is a good idea and than this happens... i will undo the rebase 😒

**Comment by d-rk** [comment]
@Am3o don't worry about it. I will get it merged somehow :)
But first I need to find the time to take a closer look at the PR.

**Comment by Am3o** [comment]
Now, it's cleaned up and we are back to the start point. Sorry for the confusing commits. 

@d-rk Take your time to proof the PR.

**Comment by d-rk** [comment]
@Am3o thank you for the PR.

I updated the PR according to the cobra docs: https://github.com/spf13/cobra/blob/master/shell_completions.md

I'm not an expert when it comes to zsh but:
- putting the `autoload` in `~/.zshrc` instead of `~/.zprofile` seems to be preferred (https://unix.stackexchange.com/a/71258/302068)
- on a new zsh installation `$ZSH/cache/completions/_kafkactl` evaluates to `/cache/completions/_kafkactl` which probably not the correct location. So I keep the location as documented in cobra docs

**Pull request merged**
