### PR TITLE
add command get brokers

### PR DESCRIPTION
**Pull request by framon**
# Description

Get the list of brokers advertised by kafka cluster. It's useful to
troubleshooting connection problems.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Documentation

- [x] the change is mentioned in the `## [Unreleased]` section of `CHANGELOG.md`
- [x] a usage example was added to `README.md`

### CODE REVIEW

**Comment by framon** [comment]
Is this a problem of the test itself?

```
=== Failed
=== FAIL: cmd/deletion TestDeleteTopicReadAclIntegration (3.31s)
    test_util.go:127: expected error to contain: topic 'acl-topic-19849' does not exist
        : Failed to get the list of partitions: kafka server: The client is not authorized to access this topic.

DONE 38 tests, 1 failure in 81.275s
```

**Comment by random-dwi** [comment]
Hey @framon, thank you for this PR. 
The test failed because the Integration tests are a bit flaky currently. So nevermind.

From a first look the change looks good. Please add an Integration test for the command. You can use https://github.com/deviceinsight/kafkactl/blob/master/cmd/create/create-topic_test.go for reference.

We don't have documentation for how to write integration tests, yet. But you can either run `make integration_test` or spin up a Kafka cluster with `docker-compose -f docker/docker-compose.yml up -d` and run the test directly in the IDE.

**Comment by framon** [comment]
@random-dwi, Thanks for your feedback. I will provide the tests in the near future.

**Comment by random-dwi** [comment]
I rebased the branch and added the missing integration tests.
This is alread merged into master. see:
https://github.com/deviceinsight/kafkactl/commit/979b9c1a6ea787680fbefe986a03163eb1623739
https://github.com/deviceinsight/kafkactl/commit/0f025dfaf5f65768bb152011191a6720dd852404

**Pull request closed without merging**
